services:
  astro-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roberto-astro-portfolio
    ports:
      - "4321:4321"
    volumes:
      # Sincronização em tempo real (Hot Reload) com o código local
      - .:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=4321
    restart: unless-stopped
